#版本配置，请勿修改
version: 1
#边界设置
boundary:
  #等级1
  1:
    #默认边界大小
    default: 10
  #等级2
  2:
    #默认边界大小
    default: 15
  #等级3
  3:
    #默认边界大小
    default: 20
  #等级4
  4:
    #默认边界大小
    default: 25
  #等级5
  5:
    #默认边界大小
    default: 30